### ISSUE TITLE
why use lock?

### ISSUE THREAD

**Issue by stallion5632** [membphis/lua-resty-test#1]
function _M.bench_once( premature, self, lock, micro_count )
    ....
    ....
    lock:unlock()
     end

    function _M.bench_back_worker( self, lock_key, micro_count )
    local lock = lock:new("cache_ngx", {timeout=4})

    local elapsed, err = lock:lock(lock_key)
    .....

    local ok, err = ngx.timer.at(0, _M.bench_once, self, lock, micro_count)
    ...
    end

I don't understand why use lock here. Isn't ngx.timer.at start a 'light thread'?(not really thread)

**Comment by membphis** [comment]
we need to control the `_M.bench_back_worker` runing one by one for the same lock_key.
